version: '3.9'

services:
  app:
    build: .
    container_name: ci-app
    image: ci-app:1.0.0
    ports:
      - 80:80
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=sample-db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

