apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-with-mysql-frontend
  labels:
    app: ci-with-mysql-frontend
spec:
  selector:
    matchLabels:
      app: ci-with-mysql-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: ci-with-mysql-frontend
    spec:
      containers:
        - name: ci-with-mysql-frontend
          image: sophy12/ci-with-mysql:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80  
